### PR TITLE
before checkout

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@memoglr force pull. control panel is at /dashboard. login_required disabled inconfig

**Comment by memoglr** [comment]
I'm havinhg this error
ModuleNotFoundError: No module named 'modules.control_panel.view'

**Comment by Abdur-rahmaanJ** [comment]
@memoglr you deleted empty control_panel folder? let me check ...

**Comment by Abdur-rahmaanJ** [comment]
Works on my side, but checking nevertheless

**Comment by Abdur-rahmaanJ** [comment]
@memoglr noton my pc, try deleting __pycache__ or an empty control_panel. I renamed control_panel to dashboard
dashboard_screenshot

**Comment by memoglr** [comment]
LGTM, 'CHECKOUT' sending error

session["option_id"] = all_data["option_id"]
KeyError: 'option_id'

**Review by memoglr — APPROVED** [review]

**Comment by Abdur-rahmaanJ** [comment]
Merged via cmd

**Pull request merged**
