### PR TITLE
Product pictures

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by memoglr** [comment]
I'm getting ModuleNotFoundError: No module named 'modules.files.view'

**Comment by Abdur-rahmaanJ** [comment]
@memoglr where? you should not get the error. Restart the app.

**Comment by memoglr** [comment]
LGTM, I had import issue with flask_uploads, I had to use Flask-Reuploaded
https://pypi.org/project/Flask-Reuploaded/

**Comment by Abdur-rahmaanJ** [comment]
@memoglr , yes! we are using reuploaded for the project. Btw the author @jugmac00 was kind enough to take an interest in Shopyo

**Comment by Abdur-rahmaanJ** [comment]
Since at least one reviewer ok for merging, feel free to merge as you finish

**Comment by Abdur-rahmaanJ** [comment]
@memoglr you are right, this is caused by an empy folder called file in modules

**Pull request merged**
