### PR TITLE
adding .travis.yml to build docs

### PR DESCRIPTION
**Pull request by sid-7**
Adding .travis.yml to build docs upon push

### CODE REVIEW

**Comment by sid-7** [comment]
can you help? I cannot figure out the error.

**Comment by sid-7** [comment]
@arthurarty  any updates on this pr?

**Comment by arthurarty** [comment]
> @arthurarty any updates on this pr?

@sid-7 Hey the error from Travis is `sphinx-build` command is not found. Now this should be because Sphinx package was not installed  since it is not listed in the requirements.txt file but rather in the dev_requirements.txt file. So you could update the .travis file to install from the dev_requirements.txt and then try again.

**Comment by Abdur-rahmaanJ** [comment]
@arthurarty i just merged another PR on same issue, closing. Thnx 4 review

**Pull request closed without merging**
