### PR TITLE
Shopyoapi to api

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis locally i get this one failing test:

```bash
============================================ FAILURES =============================================
_________________________ TestAppConfigs.test_prod_app_config[production] _________________________

self = <test_configs.TestAppConfigs object at 0x04DC8CD0>, app = <Flask 'app'>

    @pytest.mark.parametrize("app_type", ["production"])
    def test_prod_app_config(self, app):
        """
        Test the productions configs. Environment variable
        configs(private configs) are loaded from .test.prod.env just
        to make sure these are loaded correctly
        """
        config = app.config

        assert "ENV" in config
        assert config["ENV"] == "production"
        assert "DEBUG" in config
        assert config["DEBUG"] is False
        assert "SECRET_KEY" in config
>       assert config["SECRET_KEY"] == "secret"
E       AssertionError: assert None == 'secret'

tests\test_configs.py:43: AssertionError
-------------------------------------- Captured stdout setup --------------------------------------
 x Blueprint skipped: modules.box__default.settings.view
======================================== warnings summary =========================================
..\venv\lib\site-packages\_pytest\config\__init__.py:1230
  C:\Users\j\Desktop\entry\git\shopyo\venv\lib\site-packages\_pytest\config\__init__.py:1230: Pytest
ConfigWarning: Unknown config option: env_files

    self._warn_or_fail_if_strict("Unknown config option: {}\n".format(key))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================== short test summary info =====================================
FAILED tests\test_configs.py::TestAppConfigs::test_prod_app_config[production] - AssertionError: ...

============================ 1 failed, 129 passed, 1 warning in 26.57s ============================
```

Maybe we should update docs as to local configs?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis locally i get this one failing test:

```bash
============================================ FAILURES =============================================
_________________________ TestAppConfigs.test_prod_app_config[production] _________________________

self = <test_configs.TestAppConfigs object at 0x04DC8CD0>, app = <Flask 'app'>

    @pytest.mark.parametrize("app_type", ["production"])
    def test_prod_app_config(self, app):
        """
        Test the productions configs. Environment variable
        configs(private configs) are loaded from .test.prod.env just
        to make sure these are loaded correctly
        """
        config = app.config

        assert "ENV" in config
        assert config["ENV"] == "production"
        assert "DEBUG" in config
        assert config["DEBUG"] is False
        assert "SECRET_KEY" in config
>       assert config["SECRET_KEY"] == "secret"
E       AssertionError: assert None == 'secret'

tests\test_configs.py:43: AssertionError
-------------------------------------- Captured stdout setup --------------------------------------
 x Blueprint skipped: modules.box__default.settings.view
======================================== warnings summary =========================================
..\venv\lib\site-packages\_pytest\config\__init__.py:1230
  venv\lib\site-packages\_pytest\config\__init__.py:1230: Pytest
ConfigWarning: Unknown config option: env_files

    self._warn_or_fail_if_strict("Unknown config option: {}\n".format(key))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================== short test summary info =====================================
FAILED tests\test_configs.py::TestAppConfigs::test_prod_app_config[production] - AssertionError: ...

============================ 1 failed, 129 passed, 1 warning in 26.57s ============================
```

Maybe we should update docs as to local configs?

**Comment by rehmanis** [comment]
> @rehmanis locally i get this one failing test:
> 
> ```shell
> ============================================ FAILURES =============================================
> _________________________ TestAppConfigs.test_prod_app_config[production] _________________________
> 
> self = <test_configs.TestAppConfigs object at 0x04DC8CD0>, app = <Flask 'app'>
> 
>     @pytest.mark.parametrize("app_type", ["production"])
>     def test_prod_app_config(self, app):
>         """
>         Test the productions configs. Environment variable
>         configs(private configs) are loaded from .test.prod.env just
>         to make sure these are loaded correctly
>         """
>         config = app.config
> 
>         assert "ENV" in config
>         assert config["ENV"] == "production"
>         assert "DEBUG" in config
>         assert config["DEBUG"] is False
>         assert "SECRET_KEY" in config
> >       assert config["SECRET_KEY"] == "secret"
> E       AssertionError: assert None == 'secret'
> 
> tests\test_configs.py:43: AssertionError
> -------------------------------------- Captured stdout setup --------------------------------------
>  x Blueprint skipped: modules.box__default.settings.view
> ======================================== warnings summary =========================================
> ..\venv\lib\site-packages\_pytest\config\__init__.py:1230
>   C:\Users\j\Desktop\entry\git\shopyo\venv\lib\site-packages\_pytest\config\__init__.py:1230: Pytest
> ConfigWarning: Unknown config option: env_files
> 
>     self._warn_or_fail_if_strict("Unknown config option: {}\n".format(key))
> 
> -- Docs: https://docs.pytest.org/en/stable/warnings.html
> ===================================== short test summary info =====================================
> FAILED tests\test_configs.py::TestAppConfigs::test_prod_app_config[production] - AssertionError: ...
> 
> ============================ 1 failed, 129 passed, 1 warning in 26.57s ============================
> ```
> 
> Maybe we should update docs as to local configs?

It shouldn't fail unless you are missing something that is not reading the .test.prod.env or pytest.ini.  What do you mean update the docs to local configs?

**Comment by Abdur-rahmaanJ** [comment]
Explain about how Shopyo manages secrets

**Comment by rehmanis** [comment]
> Explain about how Shopyo manages secrets

Let me check if the test fails for me locally.

**Comment by rehmanis** [comment]
> > Explain about how Shopyo manages secrets
> 
> Let me check if the test fails for me locally.

@Abdur-rahmaanJ passing for me locally when checking your branch.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis you can merge i guess, works for me

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ merging.

**Pull request merged**
