### PR TITLE
Closes Issue#413

### PR DESCRIPTION
**Pull request by Shubham-Vishwakarma**

### CODE REVIEW

**Comment by Shubham-Vishwakarma** [comment]
image5

**Comment by Abdur-rahmaanJ** [comment]
AWESOME! 

Could you open a new PR and bump the project to 3.9.1? Thanks!

**Comment by Shubham-Vishwakarma** [comment]
@Abdur-rahmaanJ 
How to do this?

Should I create a new branch or something?

**Comment by rehmanis** [comment]
> @Abdur-rahmaanJ
> How to do this?
> 
> Should I create a new branch or something?

Yes just create a new PR with version update in this file https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/__init__.py

**Pull request merged**
