### PR TITLE
fix: Set logo to shopyo.png

### LINKED ISSUE #479: Set logo to shopyo.png
1. copy paste shopyo.png into sphinx_source/shopyo.png
2. change https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/sphinx_source/conf.py#L61 to shopyo.png
3. delete shopyo.ico
4. PR

### PR DESCRIPTION
**Pull request by xdshivani**
fixed: #479

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis we have some failing tests btw

**Comment by Abdur-rahmaanJ** [comment]
@xdshivani great! merging. You have Twitter, what is your username? We'd like to give you a shoutout!

Edit: Feel free to star the project ^^, this helps us make a bigger impact and reach a wider audiance!

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ if tests fail don't merge.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis this one was not related to the PR

**Comment by Abdur-rahmaanJ** [comment]
@xdshivani see the logo already appearing here: https://shopyo.readthedocs.io/en/latest/

**Comment by rehmanis** [comment]
> @rehmanis this one was not related to the PR

@Abdur-rahmaanJ It was since the name of icon was changed to .png the `new` command failed. That is why tests are present. So we make sure to update the new command as well.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis wooooooops amazing mistake, will fix

**Pull request merged**
