### PR TITLE
Added the html files using Sphinx build in Sphinx Source docs

### PR DESCRIPTION
**Pull request by ImagineZero0**
I have used the command provided with the docs in issue #163 and which added the required 33 HTML files in sphinx source docs.

This first timers only issue has really helped me to understand the whole process of contributing to open source and encouraged me to further contribute to it.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Actually you just need to include  a .travis.yml file in the root folder, with the docs build command. Not putting the docs files in sphinx_source

**Comment by ImagineZero0** [comment]
Okay, I will on it right away, Thanx for the advice.

**Comment by ImagineZero0** [comment]
@Abdur-rahmaanJ Could you check my PR... I have made the required changes to the repository..?

Could you please review it?

**Comment by Abdur-rahmaanJ** [comment]
The command is right but, one thing, that's not what is there in  a Travis script. Please see what a travis script looks like and where should you put the command!

**Comment by ImagineZero0** [comment]
Hey @Abdur-rahmaanJ,
I had a doubt regarding the .tarvis.yml file...
I am making the file as required and installing all the dependencies but when running the Travis ci on my branch it is giving some error that I cannot understand...
could you look at it?

`
language : ruby            
`

`
before_install:
    - pip install Sphinx
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install Werkzeug
    - pip install flask-marshmallow
    - pip install coverage
    - pip install Flask-Migrate
    - pip install Flask-Script
    - pip install Flask-Login
    - pip install Flask-WTF
    - pip install Flask-Testing
    - pip install flake8
    - pip install marshmallow-sqlalchemy
    - pip install requests
    - pip install pytest
    - pip install selenium
`

`
script:
    - sphinx-build -b html sphinx_source docs
`

And the Error you can look at it at this link-
https://travis-ci.com/github/ImagineZero0/shopyo/jobs/400049717#L7

**Pull request closed without merging**
