### PR TITLE
Moved get_setting from enhance to helpers and changed imports

### LINKED ISSUE #343: Remove settings codes from shopyoapi
move get_setting from shopyoapi/enhance.py to settings/helpers.py

### PR DESCRIPTION
**Pull request by Yahyakiani**
Resolves #343 

I should mention the helpers file was not in setting but shop.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@Yahyakiani we meant to create a new helpers file in setting. Could you fix? Thanks!

**Comment by Yahyakiani** [comment]
@Abdur-rahmaanJ Last issue will be resolved while merging cause I am not seeing the unused import on my local branch.

**Comment by Abdur-rahmaanJ** [comment]
Great! It's ok. There is a fix which is needed. instead of importing get setting in shopyoapi, replace all imports of get setting from shopyoapi everywhere by importing from box__default.settings.helpers


@Yahyakiani you prefer to apply the fix in this PR or another one? If another one, i'll merge this one!

**Comment by Yahyakiani** [comment]
@Abdur-rahmaanJ i ll do it it another issue.Assign that one to me and you can merge this one. Thanks

**Comment by Abdur-rahmaanJ** [comment]
Ok!

**Comment by Abdur-rahmaanJ** [comment]
@Yahyakiani comment here: https://github.com/Abdur-rahmaanJ/shopyo/issues/366 to let github allow me to assign you. thanks!

**Pull request merged**
