### PR TITLE
Product subcategory

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@memoglr  must reinitialise app

**Comment by memoglr** [comment]
Have multiple issues when running the app:
trying loader of application "app"
trying loader of blueprint "admin" (modules.admin.view)
trying loader of blueprint "appointment" (modules.appointment.view)
trying loader of blueprint "base" (modules.base.view)
trying loader of blueprint "category" (modules.category.view)
trying loader of blueprint "contact" (modules.contact.view)
trying loader of blueprint "control_panel" (modules.control_panel.view)
trying loader of blueprint "www" (modules.www.view)
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:

**Comment by Abdur-rahmaanJ** [comment]
@memoglr i enabled template debugging in development config

**Review by memoglr — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
