### PR TITLE
Update user login

### PR DESCRIPTION
**Pull request by NicoPlyley**
Database results and form submission are compared in lowercase. This will keep backwards compatibility vs storing all email in lower case and converting from submission to lowercase. 

And unused import requests was also removed

Solves #394

### CODE REVIEW

**Comment by rehmanis** [comment]
@NicoPlyley Perfect. Much more elegant and simple solution than what I had in mind. The only problem is that I can now register both users for example with emails "admin2@gmail.com" and "Admin2@gmail.com" in the Users model and when you login it will just grab the first one. You can try registering at http://localhost:5000/auth/register with admin2@gmail.com and Admin2@gmail.com. Set the `EMAIL_CONFIRMATION_DISABLED = True`  in class `DevelopmentConfig`  of `config.py` file if you want to see the dashboard when logging in with the newly registered user.

To fix this you might have to add `@validates("email")` in the user model as explain in the issue #397 so that we save the email in lower case in database. You will also have to change `def validate_email(self, field):` in form.py of the `auth` module.

Once all is good then you can add some tests like below. You can change as needed.

```python
    # add this in class TestUser of test_auth_model.py
    def test_email_is_case_insensitive(self):
        User.create(email="Foo@baR.com", password="pass")

        with pytest.raises(IntegrityError):
            User.create(email="foo@bar.com", password="another")
```

```python
    # add this in TestAuthEndpoints class of test_auth_functional.py
    def test_email_case_does_not_affect_login(self, test_client):

        user = User()
        user.email = "teSt@doMain.com"
        user.password = "pass"
        user.is_email_confirmed = True
        user.save()

        response = test_client.post(
            url_for("auth.login"),
            data=dict(email="tesT@DOmain.com", password="pass"),
            follow_redirects=True,
        )

        assert response.status_code == 200
        assert request.path == url_for("dashboard.index")
```

**Comment by NicoPlyley** [comment]
Good catch, I surprised I didn't see that. My suggestion would be to just update the validation to the same query. That way both are the exact same.

So the validation would be ` user = User.query.filter(func.lower(User.email) == func.lower(field.data)).scalar()`

 Unless you do not want emails to be upper and lower case in the database. I feel like that decision should be made first and then I can update accordingly @rehmanis

**Comment by rehmanis** [comment]
@NicoPlyley yes just change `form.py` file's `validate_email` function for now. In addition to registering, an admin is be able to add the users manually as well. You can test this by going to http://localhost:5000/admin/add (having logged in with `email "admin@domain.com"` and `password "pass"`). But this admin module will be replaced by `flask_admin` in PR https://github.com/Abdur-rahmaanJ/shopyo/pull/396  so if you want you can then fix the email case part of it as well in next PR/issue.

Few tips/suggestions:
- You can use `filter_by` instead of `filter` as it makes it easier for reading code and (and you write smaller code) for simple query like this one. For example: `user = User.query.filter_by(email=field.data.lower()).scalar()`. But I leave this to your discretion.
- use `flake8` to fix the pep8 linting errors that you see in above pep8speaks comment. See step 8 of https://www.appinv.science/shopyo/contrib.html#making-a-pull-request

**Comment by NicoPlyley** [comment]
@rehmanis The reason I used filter and not filer_by was because I am converting a result from the database into lower case and checking it against the form, that way it does not matter the database entry case, otherwise if the email was not stored in lowercase it would fail

**Comment by rehmanis** [comment]
@NicoPlyley yes correct my bad. In that case it would wise to add multiple test cases. For example, Test case 1 for the case when the data in DB is mixed case while data from form is lowercase. And test case 2 where the data in DB is lowercase while data in form is mixed case etc.

update: 
Maybe one test case as shown above for this might be enough as it convers both cases. Anyways I leave it you to decide. Also you can post in our [discord](https://discord.com/invite/k37Ef6w) for more active discussion.

**Comment by NicoPlyley** [comment]
@rehmanis I believe all functionality and testing has been completed. Please review and let me know

**Comment by NicoPlyley** [comment]
I see there is an error should I change it to confirm since the confirm email config is not set for this version? Or is there a different user I should check against?

**Comment by rehmanis** [comment]
> I see there is an error should I change it to confirm since the confirm email config is not set for this version? Or is there a different user I should check against?

Looks all good. You can just add `is_email_confirm=True` when doing `User.create(...)`. Or change the assert check to `assert request.path == url_for("auth.unconfirmed")`. To test locally you can run `python -m pytest -k "test_valid_dashboard_login_is_case_insensitive"  -v`. To run all tests just do `python -m pytest`

**Comment by rehmanis** [comment]
@NicoPlyley Perfect. Thank you for the PR.
Merging. Feel free to raise other issue, improvements etc.

**Pull request merged**
