### PR TITLE
Flask admin integration

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis Travis no longer works?

**Comment by rehmanis** [comment]
> @rehmanis Travis no longer works?

@Abdur-rahmaanJ see my pull request comment #392. Merging that will start the GitHub actions. Travis not working.

**Comment by Abdur-rahmaanJ** [comment]
Hum ok

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis i added a next input in login form, causing isssues with tests

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ I will to check this locally. Don't merge until tests pass.

**Pull request merged**
