### PR TITLE
Adding travis file

### PR DESCRIPTION
**Pull request by ImagineZero0**
I have added the respective .travis.yml file.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Cool just ... language you added ruby

**Comment by Abdur-rahmaanJ** [comment]
Also, yml is not json. Put it in .yml format. Values and data ok

**Comment by ImagineZero0** [comment]
Hey @Abdur-rahmaanJ,
I did the required changes for the format and the language but it seems to still give a particular error in the same portion of the code...

**Comment by Abdur-rahmaanJ** [comment]
@ImagineZero0 np lol npw we are adding the travis script. dnt mind it

**Pull request merged**
