### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by akshay4n**
#316 
@Abdur-rahmaanJ Could you guide me with the errors

### CODE REVIEW

**Comment by rehmanis** [comment]
@akshay4n the error was due to latest code being broken. It is now fixed but needs you to grab the latest changes by doing the following:

```bash
git checkout dev
git fetch upstream dev
git pull upstream dev
git checkout patch-1
git merge dev
```
then run the tests to make sure its passing locally as follows:
```bash
python -m pytest
```
Then add your commit again:
```bash
git add .
git commit -m "merge latest changes"
git push origin head
```

**Comment by rehmanis** [comment]
Actually I will just merge since this will get fixed once merged.

**Comment by Abdur-rahmaanJ** [comment]
@akshay4n We'd be really grateful if you star the project!

Feel free to join our [discord](https://discord.gg/k37Ef6w) for tougher issues!

**Comment by akshay4n** [comment]
@Abdur-rahmaanJ Thanks for guiding!

**Pull request merged**
